[commands.manage]
smart-decompress-directory = true
search-file = true
output-file-action = "decompress-to-output-dir"
compressed-file-action = "move-to-archive-dir"

[commands.manage.directories]
search = "search"
output = "output"
archive = "archive"

[formats.zip]
extensions = ["zip"]

[[formats.zip.decompress]]
path = "7z"
args = ["x", "{FILE}", "-o{DIR}"]

[[formats.zip.decompress]]
path = "unzip"
args = ["{FILE}", "-d", "{DIR}"]

[formats.rar]
extensions = ["rar"]

[[formats.zip.decompress]]
path = "7z"
args = ["x", "{FILE}", "-o{DIR}"]

[[formats.rar.decompress]]
path = "unrar"
args = ["x", "{FILE}", "{DIR}"]

[formats.7z]
extensions = ["7z"]

[[formats.zip.decompress]]
path = "7z"
args = ["x", "{FILE}", "-o{DIR}"]
